DROP FUNCTION IF EXISTS CHOROBY_I_LEKI
GO

CREATE FUNCTION CHOROBY_I_LEKI
(
@nr_paszportu VARCHAR(250)
)
RETURNS TABLE
AS
RETURN 
(
	SELECT 
		(SELECT IMIE FROM KONIE k WHERE k.NR_PASZPORTU = ch.NR_PASZPORTU) AS IMIE, 
		ch.CHOROBA, l.DATA_PODANIA,
		(SELECT s.NAZWA FROM SPIS_LEKOW s WHERE s.ID_LEKU = l.ID_LEKU) AS LEK
	FROM LEKI l JOIN CHOROBY ch ON l.ID_CHOROBY = ch.ID_CHOROBY
	WHERE ch.NR_PASZPORTU = @nr_paszportu
)
GO

SELECT * FROM [dbo].CHOROBY_I_LEKI('616 034 92 00234 61')
GO

DROP FUNCTION IF EXISTS TRENINGI_KONIA
GO

CREATE FUNCTION TRENINGI_KONIA
(
@nr_paszportu VARCHAR(250)
)
RETURNS TABLE
AS
RETURN 
(
	SELECT (SELECT k.IMIE FROM KONIE k WHERE k.NR_PASZPORTU = t.NR_PASZPORTU) AS KON,
	t.DATA_TRENINGU, t.CZAS_TRWANIA_H, 
	((SELECT j.IMIE FROM JEZDZCY j WHERE j.ID_JEZDZCA = t.JEZDZIEC) + 
	' ' + (SELECT j.NAZWISKO FROM JEZDZCY j WHERE j.ID_JEZDZCA = t.JEZDZIEC)) AS JEZDZIEC,
	((SELECT j.IMIE FROM TRENERZY j WHERE j.ID_TRENERA = t.TRENER) + 
	' ' + (SELECT j.NAZWISKO FROM TRENERZY j WHERE j.ID_TRENERA = t.TRENER)) AS TRENER
	FROM TRENINGI t
	WHERE t.NR_PASZPORTU = @nr_paszportu
)
GO

SELECT * FROM [dbo].TRENINGI_KONIA('616 034 92 00234 61')
GO

DROP FUNCTION IF EXISTS TRENINGI_Z_DNIA
GO

CREATE FUNCTION TRENINGI_Z_DNIA
(
@data DATE
)
RETURNS TABLE
AS
RETURN 
(
	SELECT (SELECT k.IMIE FROM KONIE k WHERE k.NR_PASZPORTU = t.NR_PASZPORTU) AS KON,
	t.DATA_TRENINGU, t.CZAS_TRWANIA_H, 
	((SELECT j.IMIE FROM JEZDZCY j WHERE j.ID_JEZDZCA = t.JEZDZIEC) + 
	' ' + (SELECT j.NAZWISKO FROM JEZDZCY j WHERE j.ID_JEZDZCA = t.JEZDZIEC)) AS JEZDZIEC,
	((SELECT j.IMIE FROM TRENERZY j WHERE j.ID_TRENERA = t.TRENER) + 
	' ' + (SELECT j.NAZWISKO FROM TRENERZY j WHERE j.ID_TRENERA = t.TRENER)) AS TRENER,
	t.OPIS
	FROM TRENINGI t
	WHERE t.DATA_TRENINGU = @data
)
GO

SELECT * FROM [dbo].TRENINGI_Z_DNIA('2019-01-14')
GO

DROP FUNCTION IF EXISTS DZIECI
GO

CREATE FUNCTION DZIECI
(
@nr_paszportu VARCHAR(250)
)
RETURNS TABLE 
AS
RETURN
(	
	SELECT k.NR_PASZPORTU, k.IMIE, k.DATA_URODZENIA, k.RASA, k.PLEC, k.WLASCICIEL, k.WZROST
	FROM KONIE k
	WHERE @nr_paszportu = k.MATKA_PASZPORT
)
GO

SELECT * FROM [dbo].DZIECI('616 886 34 00987 34')
GO

DROP FUNCTION IF EXISTS TRENING_TRENERA
GO

CREATE FUNCTION TRENING_TRENERA
(
@imie VARCHAR(250),
@nazwisko VARCHAR(250)
)
RETURNS TABLE
AS
RETURN
(
	SELECT t.DATA_TRENINGU, t.NR_PASZPORTU, (SELECT IMIE FROM KONIE WHERE NR_PASZPORTU = t.NR_PASZPORTU) AS KON,
	t.OPIS, t.JEZDZIEC
	FROM TRENINGI t JOIN TRENERZY t2 ON t.TRENER = t2.ID_TRENERA
	WHERE t2.IMIE = @imie AND t2.NAZWISKO = @nazwisko
)
GO

SELECT * FROM [dbo].TRENING_TRENERA('Julia','Michalak')
GO