DROP FUNCTION IF EXISTS GODZINY_TRENINGU
GO

CREATE FUNCTION GODZINY_TRENINGU
(
@nr_paszportu VARCHAR(250)
)
RETURNS DECIMAL(5,2)
AS
BEGIN
DECLARE @suma DECIMAL(5, 3);

SELECT @suma = SUM(t.CZAS_TRWANIA_H) from TRENINGI t
WHERE t.NR_PASZPORTU = @nr_paszportu

RETURN @suma

END
GO

SELECT [dbo].GODZINY_TRENINGU('616 034 92 00234 61')
GO

DROP FUNCTION IF EXISTS ILOSC_KONI_WLASCICIELA
GO

CREATE FUNCTION ILOSC_KONI_WLASCICIELA
(
@id_wlasciciela INT
)
RETURNS INT
AS
BEGIN
DECLARE @ilosc INT;

SELECT @ilosc = COUNT(NR_PASZPORTU) from KONIE k
WHERE k.WLASCICIEL = @id_wlasciciela

RETURN @ilosc

END
GO

SELECT [dbo].ILOSC_KONI_WLASCICIELA(5)
GO

DROP FUNCTION IF EXISTS AVG_JEZDZCY
GO

CREATE FUNCTION AVG_JEZDZCY
(
)
RETURNS DECIMAL(5,2)
AS
BEGIN
DECLARE @avg DECIMAL(5,2);

SELECT @avg = AVG(j.WIEK) FROM JEZDZCY j

RETURN @avg

END
GO

SELECT [dbo].AVG_JEZDZCY()
GO